version: 0.1

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::697877139013:role/service-role/codebuild-LRS-service-role
  ComputeType: Linux
  Image: aws/codebuild/nodejs:6.3.1
  Timeout: 60

phases:
  install:
    commands:
      - echo "npm install"
  pre_build:
    commands:
      - echo "./node_modules/.bin/gulp eslint"
  build:
    commands:
      - echo "build phase"
  post_build:
    commands:
      - for i in $(ls node_modules | grep -v ^lrs-); do rm -Rf node_modules/$i; done

artifacts:
  files:
    - '.bowerrc'
    - '.ebextensions/*'
    - '.elasticbeanstalk/*'
    - '.gitignore'
    - '**/*'
